queue_rules:
- name: default
  speculative_checks: 20
  batch_size: 20
  conditions:
  - status-success=lint
  - status-success=lint-markdown
  - status-success=test
  - status-success=docker-build
  - status-success=versio-plan

pull_request_rules:
- name: automatic rebase for dependencies
  conditions:
  - status-success=lint
  - status-success=lint-markdown
  - status-success=test
  - status-success=docker-build
  - status-success=versio-plan
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    queue:
      method: rebase
      rebase_fallback: merge
      name: default
