options:
  prev_tag: "versio-prev"

projects:
  - name: "gfmfmt"
    id: 1
    tag_prefix: ""
    labels: docker
    version:
      tags:
        default: "0.1.0"
    also:
    - file: README.md
      pattern: PurpleBooth/gfmfmt-action@v(\d+\.\d+\.\d+)
sizes:
  use_angular: true
  none: ["-", "ci"]
