name: gfmfmt action
description: Uses pandoc to lint and optionally format markdown to a standard format
inputs:
  check:  # id of input
    description: If "false" will format the markdown
    required: false
    default: 'true'
  pattern:  # id of input
    description: Pattern to filter files by
    required: false
    default: ^(?!\./\.github/ISSUE_TEMPLATE/).*\.md$
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.check }}
  - ${{ inputs.pattern }}
branding:
  icon: award
  color: blue
