name: gfmfmt action
description: Uses pandoc to lint and optionally format markdown to a standard format
inputs:
  check:  # id of input
    description: If "false" will format the markdown
    required: false
    default: 'true'
  path:  # id of input
    description: Path to search within for markdown files
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.check }}
  - ${{ inputs.path }}
branding:
  icon: award
  color: blue
